name: RDP-FREE-BR

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM | siga meu instagram @heltonleiras 
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/LW-BACKUP/W10_RDP/main/Files/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/LW-BACKUP/W10_RDP/main/Files/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory. | siga meu instagram @heltonleiras
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account | siga meu instagram @heltonleiras
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files. | siga meu instagram @heltonleiras
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/LW-BACKUP/W10_RDP/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/LW-BACKUP/W10_RDP/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/LW-BACKUP/W10_RDP/main/Files/loop.bat -OutFile loop.bat
    - name: Make YML file for NGROK. | siga meu instagram @heltonleiras
      run: start NGROK-US.bat
    - name: Enable RDP Access. | siga meu instagram @heltonleiras
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel | siga meu instagram @heltonleiras
      run: sc start ngrok
    - name: Connect to your RDP 2core-7GB Ram. | siga meu instagram @heltonleiras
      run: cmd /c NGROK-CHECK.bat
    - name: Entre no meu Grupo do discord https://bit.ly/moonumbrella
      run: cmd /c loop.bat 
